# Generated by Django 4.0.2 on 2022-02-27 03:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, null=True, verbose_name='Updated At')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
